name: Build

on:
  push:
    branches: ["master", "dev"]
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, DebugDLL, Release, ReleaseDLL, ProductionRelease, ProductionReleaseDLL]

    steps:
    - uses: actions/checkout@v3
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.configuration }}
        path: bin/${{ matrix.configuration }}-x64
  
  variables:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - uses: LazyPanda07/extract-current-branch@v1.0.0

    - name: Print branch
      run: echo ${{ env.CURRENT_BRANCH }} # print dev or distribute

    - uses: LazyPanda07/extract-current-branch@v1.0.0
      with:
        variable-name: custom-branch # override default variable name to custom-branch

    - name: Print custom branch
      run: echo ${{ env.custom-branch }} # print dev or distribute
