name: Publish

on:
  workflow_run:
    workflows: ["Tests"]
    branches: ["master"]
    types: 
      - completed
      
jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@master
      with:
        workflow: build.yml
      
    - name: Setup release version variable
      shell: pwsh
      run: echo "UTILITY_LIBRARY_VERSION=$($($($(Select-String -Path .\src\Defines.h -Pattern utilityLibraryVersion) -split '( = )')[2].TrimEnd(';')).Trim('\"'))" >> $Env:GITHUB_ENV
      
    - name: Setup archive name variable
      shell: pwsh
      run: echo "UTILITY_LIBRARY_ARCHIVE_NAME=UtilityLibrary_${{ env.UTILITY_LIBRARY_VERSION }}.zip" >> $Env:GITHUB_ENV

    - name: Create zip
      shell: pwsh
      run: Compress-Archive -Path @("Debug", "DebugDLL", "Release", "ReleaseDLL", "ProductionRelease", "ProductionReleaseDLL") -DestinationPath ${{ env.UTILITY_LIBRARY_ARCHIVE_NAME }}
      
    - name: Publish
      uses: svenstaro/upload-release-action@master
      with:
        tag: ${{ env.UTILITY_LIBRARY_VERSION }}
        file: ${{ env.UTILITY_LIBRARY_ARCHIVE_NAME }}
    