name: Publish

on:
  workflow_run:
    workflows: ["Tests"]
    branches: ["master"]
    types: 
      - completed
      
jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@master
      with:
        workflow: build.yml
      
    - name: Set release version
      shell: pwsh
      run: echo "UTILITY_LIBRARY_VERSION=$($($(Select-String -Path .\src\Defines.h -Pattern utilityLibraryVersion) -split '( = )')[2].TrimEnd(';'))" >> $Env:GITHUB_ENV
      
    - name: Create zip
      shell: pwsh
      run: Compress-Archive -Path @("Debug", "DebugDLL", "Release", "ReleaseDLL", "ProductionRelease", "ProductionReleaseDLL") -DestinationPath UtilityLibrary_${{ env.UTILITY_LIBRARY_VERSION }}.zip

    - name: Directory
      run: dir

    - name: Publish
      uses: svenstaro/upload-release-action@master
      with:
        tag: ${{ env.UTILITY_LIBRARY_VERSION }}
        asset_name: UtilityLibrary_${{ env.UTILITY_LIBRARY_VERSION }}.zip
    