name: Release

on:
  workflow_run:
    workflows: ["Tests"]
    branches: ["dev"]
    types: 
      - completed

jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, DebugDLL, Release, ReleaseDLL, ProductionRelease, ProductionReleaseDLL]

    steps:
    - uses: actions/checkout@v3
  
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@master
      with:
        name: ${{ matrix.configuration }}
        workflow: build.yml

    - name: Release
      run: echo "Release"

    - name: Downloaded artifacts
      run: dir
