name: Release

on:
  workflow_run:
    workflows: ["Tests"]
    branches: ["master"]
    types: 
      - completed
      
jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@master
      with:
        workflow: build.yml
      
    - name: Set release version
      shell: pwsh
      # run: echo "UTILITY_LIBRARY_VERSION=$($(Select-String -Path .\src\Defines.h -Pattern utilityLibraryVersion) -split '( = )')[2]" >> $GITHUB_ENV
      run: echo "UTILITY_LIBRARY_VERSION=0.1.0" >> $GITHUB_ENV

    - name: Test
      run: echo ${{ env.UTILITY_LIBRARY_VERSION }}
