name: Release

on:
  workflow_run:
    workflows: ["Build", "Tests"]
    branches: ["dev"]
    types: 
      - completed

jobs:
  release:
    needs: build

    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, DebugDLL, Release, ReleaseDLL, ProductionRelease, ProductionReleaseDLL]

    steps:
    - uses: actions/checkout@v3
  
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.configuration }}-x64

    - name: Release
      run: echo "Release"

    - name: Downloaded artifacts
      run: dir
