name: Tests

on:
  workflow_run:
    workflows: ["Build"]
    branches: ["master", "dev"]
    types:
      - completed

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, DebugDLL, Release, ReleaseDLL, ProductionRelease, ProductionReleaseDLL]

    steps:
    - uses: actions/checkout@v3
  
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@master
      with:
        name: ${{ matrix.configuration }}
        workflow: build.yml
